from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.address import Address
from openapi_server import util

from openapi_server.models.address import Address  # noqa: E501

class CheckAddressTaxabilityRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address=None):  # noqa: E501
        """CheckAddressTaxabilityRequest - a model defined in OpenAPI

        :param address: The address of this CheckAddressTaxabilityRequest.  # noqa: E501
        :type address: Address
        """
        self.openapi_types = {
            'address': Address
        }

        self.attribute_map = {
            'address': 'address'
        }

        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'CheckAddressTaxabilityRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CheckAddressTaxabilityRequest of this CheckAddressTaxabilityRequest.  # noqa: E501
        :rtype: CheckAddressTaxabilityRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> Address:
        """Gets the address of this CheckAddressTaxabilityRequest.


        :return: The address of this CheckAddressTaxabilityRequest.
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address: Address):
        """Sets the address of this CheckAddressTaxabilityRequest.


        :param address: The address of this CheckAddressTaxabilityRequest.
        :type address: Address
        """

        self._address = address
