from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.customer import Customer
from openapi_server.models.seller import Seller
from openapi_server.models.tax_estimation_line_item_request import TaxEstimationLineItemRequest
from openapi_server import util

from openapi_server.models.customer import Customer  # noqa: E501
from openapi_server.models.seller import Seller  # noqa: E501
from openapi_server.models.tax_estimation_line_item_request import TaxEstimationLineItemRequest  # noqa: E501

class TaxEstimationRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, seller=None, customer=None, estimate_date_time=None, currency=None, line_items=None):  # noqa: E501
        """TaxEstimationRequest - a model defined in OpenAPI

        :param seller: The seller of this TaxEstimationRequest.  # noqa: E501
        :type seller: Seller
        :param customer: The customer of this TaxEstimationRequest.  # noqa: E501
        :type customer: Customer
        :param estimate_date_time: The estimate_date_time of this TaxEstimationRequest.  # noqa: E501
        :type estimate_date_time: datetime
        :param currency: The currency of this TaxEstimationRequest.  # noqa: E501
        :type currency: str
        :param line_items: The line_items of this TaxEstimationRequest.  # noqa: E501
        :type line_items: List[TaxEstimationLineItemRequest]
        """
        self.openapi_types = {
            'seller': Seller,
            'customer': Customer,
            'estimate_date_time': datetime,
            'currency': str,
            'line_items': List[TaxEstimationLineItemRequest]
        }

        self.attribute_map = {
            'seller': 'seller',
            'customer': 'customer',
            'estimate_date_time': 'estimateDateTime',
            'currency': 'currency',
            'line_items': 'lineItems'
        }

        self._seller = seller
        self._customer = customer
        self._estimate_date_time = estimate_date_time
        self._currency = currency
        self._line_items = line_items

    @classmethod
    def from_dict(cls, dikt) -> 'TaxEstimationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaxEstimationRequest of this TaxEstimationRequest.  # noqa: E501
        :rtype: TaxEstimationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def seller(self) -> Seller:
        """Gets the seller of this TaxEstimationRequest.


        :return: The seller of this TaxEstimationRequest.
        :rtype: Seller
        """
        return self._seller

    @seller.setter
    def seller(self, seller: Seller):
        """Sets the seller of this TaxEstimationRequest.


        :param seller: The seller of this TaxEstimationRequest.
        :type seller: Seller
        """
        if seller is None:
            raise ValueError("Invalid value for `seller`, must not be `None`")  # noqa: E501

        self._seller = seller

    @property
    def customer(self) -> Customer:
        """Gets the customer of this TaxEstimationRequest.


        :return: The customer of this TaxEstimationRequest.
        :rtype: Customer
        """
        return self._customer

    @customer.setter
    def customer(self, customer: Customer):
        """Sets the customer of this TaxEstimationRequest.


        :param customer: The customer of this TaxEstimationRequest.
        :type customer: Customer
        """
        if customer is None:
            raise ValueError("Invalid value for `customer`, must not be `None`")  # noqa: E501

        self._customer = customer

    @property
    def estimate_date_time(self) -> datetime:
        """Gets the estimate_date_time of this TaxEstimationRequest.

        The time as of which the tax estimation is to be calculated. This can be a value in the past. For example, if the value is provided as 2022-10-28T15:36:28.129+05:30, then the tax rates applicable on October 28, 2022, at 15:36:28.129, with an offset of +05:30 ahead of UTC/GMT are used for calculations. In case of a merchant site located in UTC, these data types would send a timestamp in the format 2022-11-11T15:40:44.65Z. This timestamp represents November 11, 2022, at 15:40:44.65, with the 'Z' indicating that the time is in UTC  # noqa: E501

        :return: The estimate_date_time of this TaxEstimationRequest.
        :rtype: datetime
        """
        return self._estimate_date_time

    @estimate_date_time.setter
    def estimate_date_time(self, estimate_date_time: datetime):
        """Sets the estimate_date_time of this TaxEstimationRequest.

        The time as of which the tax estimation is to be calculated. This can be a value in the past. For example, if the value is provided as 2022-10-28T15:36:28.129+05:30, then the tax rates applicable on October 28, 2022, at 15:36:28.129, with an offset of +05:30 ahead of UTC/GMT are used for calculations. In case of a merchant site located in UTC, these data types would send a timestamp in the format 2022-11-11T15:40:44.65Z. This timestamp represents November 11, 2022, at 15:40:44.65, with the 'Z' indicating that the time is in UTC  # noqa: E501

        :param estimate_date_time: The estimate_date_time of this TaxEstimationRequest.
        :type estimate_date_time: datetime
        """
        if estimate_date_time is None:
            raise ValueError("Invalid value for `estimate_date_time`, must not be `None`")  # noqa: E501

        self._estimate_date_time = estimate_date_time

    @property
    def currency(self) -> str:
        """Gets the currency of this TaxEstimationRequest.

        The [currency](https://en.wikipedia.org/wiki/Currency) in the [ISO-4217 format](https://www.iso.org/iso-4217-currency-codes.html).  # noqa: E501

        :return: The currency of this TaxEstimationRequest.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this TaxEstimationRequest.

        The [currency](https://en.wikipedia.org/wiki/Currency) in the [ISO-4217 format](https://www.iso.org/iso-4217-currency-codes.html).  # noqa: E501

        :param currency: The currency of this TaxEstimationRequest.
        :type currency: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501
        if currency is not None and len(currency) > 3:
            raise ValueError("Invalid value for `currency`, length must be less than or equal to `3`")  # noqa: E501
        if currency is not None and len(currency) < 3:
            raise ValueError("Invalid value for `currency`, length must be greater than or equal to `3`")  # noqa: E501

        self._currency = currency

    @property
    def line_items(self) -> List[TaxEstimationLineItemRequest]:
        """Gets the line_items of this TaxEstimationRequest.

        Contains the details of each line item in the tax estimation request.  # noqa: E501

        :return: The line_items of this TaxEstimationRequest.
        :rtype: List[TaxEstimationLineItemRequest]
        """
        return self._line_items

    @line_items.setter
    def line_items(self, line_items: List[TaxEstimationLineItemRequest]):
        """Sets the line_items of this TaxEstimationRequest.

        Contains the details of each line item in the tax estimation request.  # noqa: E501

        :param line_items: The line_items of this TaxEstimationRequest.
        :type line_items: List[TaxEstimationLineItemRequest]
        """
        if line_items is None:
            raise ValueError("Invalid value for `line_items`, must not be `None`")  # noqa: E501
        if line_items is not None and len(line_items) > 1250:
            raise ValueError("Invalid value for `line_items`, number of items must be less than or equal to `1250`")  # noqa: E501
        if line_items is not None and len(line_items) < 1:
            raise ValueError("Invalid value for `line_items`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._line_items = line_items
