/*
Taxes Service Adapter SPI

Testing CreditNoteAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CreditNoteAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CreditNoteAPIService CommitCreditNote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var creditNoteId string

		httpRes, err := apiClient.CreditNoteAPI.CommitCreditNote(context.Background(), creditNoteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CreditNoteAPIService CreateCreditNote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CreditNoteAPI.CreateCreditNote(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CreditNoteAPIService FetchCreditNote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var creditNoteId string

		resp, httpRes, err := apiClient.CreditNoteAPI.FetchCreditNote(context.Background(), creditNoteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CreditNoteAPIService VoidCreditNote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var creditNoteId string

		httpRes, err := apiClient.CreditNoteAPI.VoidCreditNote(context.Background(), creditNoteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
